apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bdivwGvvUivZHuBrzE/GpwbxDR4NsKHwew94NucAOcbKX7EQkZlIVy9xuZ2SCe3agFx/zvsCpy8fwltMkBTxViksmrMcfhqgQi1Ien1KhNnquSbXa3vtTx2GTFO24ws8Bfn7FP7y+ECEp7dG8NoPynFNbxGuEQv0CiDkxeyu+BI9bHfaPEWUv8/9T2ArYyDdwT0F40xKIG0PRHwXkaFD1JaguqUk1OmdFy+b8wkDPNfptI8XQH6dkcrFOr1U1wS/QjHSDA8PlA6gUiIybUwZJ6O1EKE4GhvzLTzuCE1oP7O0wKxPvJjUwK5ojSc=,iv:ToAFhurA6B64Bsb6Ez4wjsBKquMX68psRTvNCccnQz0=,tag:JHXNhrdlvO+0HlNSMBKQdw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWVpUV0lkZG9nR1BtZHND
            SnhySnJxazlMT0tDMjBrMGFndXZPYU51VGtnCnZycXpqZDk3a0FvTEJ1QTFNZXkv
            dXhTMGEyWm9IL0lZU2k4aktXaU1ROXcKLS0tIHN6MzF3MUtnOFFRNElWS1A0dkZS
            WEhDNnZWZE93ckFsakw3SjFoeWcwZnMKZvvjYAkz4jgrALYD2NFrPz5avhHyD6BE
            nQzQxEPOxWhVXUiTa77N3qPw4DBJYNEfw+rLVasSDVZhSD8e+48+NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwj88ytl2haqdelv3nva4jv3c0l8m7vr85lrvcjyhxkt3smxe44q5pm6jg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T00:43:51Z"
    mac: ENC[AES256_GCM,data:TF5FyxqxwIYVstMXZqSrsOnO4SF6qmJCwUHQbQxoADH6tJZH4y+uJFjNs45cn4H6ngUPKOsDam6D6CdLC5/jpLWx358ZKVeocvOWnyAM56hgUlMGo4kI5YHPGleYi+Fc1Of3Gkknx/cQI1e9dyZAzyVCxZrVHp3IXbt7yzhBARg=,iv:26Nm1X0W3Y7MilL2yTl71UWRmAHqiFzsfQBgINLToCE=,tag:jrVIEgiZ0LvtszbC8T/Wqg==,type:str]
    version: 3.13.2
